title: "Levity Cube"
description: "Independent game studio in Ontario, Canada. Maker of Cellar Creek and My Mochi 97."
url: "https://levitycube.com"
baseurl: ""
permalink: /updates/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE.md
  - README.md
  - sitemap.xml
  - landing-editorial.html
  - landing.html
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
